name: tinode
description: This SDK implements Tinode client-side protocol for multi platform applications based on dart. 
version: 1.0.0-alpha.4
homepage: https://tinode.co/

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  rxdart: ^0.27.7
  web_socket_channel: ^2.2.0
  get_it: ^7.2.0
  equatable: ^2.0.5
  logger: ^1.1.0
  intl: ^0.17.0
  objectbox: ^1.5.0
  objectbox_flutter_libs: any
  connectivity_plus: ^3.0.2

dependency_overrides:
  archive: ^3.0.0
  convert: ^3.0.0
  crypto: ^3.0.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.5
  objectbox_generator: any
  build_runner: 2.3.2

objectbox:
  output_dir: src/database